### ISSUE TITLE
Segfault on "Grim Reaper" screen

### ISSUE THREAD

**Issue by stephengtuggy** [vegastrike/Vega-Strike-Engine-Source#351]
aka "Game dies right after player dies." 😝 

When I die in Vega Strike, and I leave this screen open for 20 seconds or so:

![Screenshot from 2020-11-29 13-11-23](https://user-images.githubusercontent.com/13305766/100553750-7bbbc400-3244-11eb-9fde-31e8302e227e.png)

I get a segfault:

![Screenshot from 2020-11-29 13-12-56](https://user-images.githubusercontent.com/13305766/100553776-a279fa80-3244-11eb-9779-716ac31279b3.png)

I should be able to respawn from this screen by pressing ';', but that isn't possible, because the entire game crashes. Alternatively, if I press ';' right away, then the annoying "beep, beep" noise keeps going indefinitely as I resume playing. That's why I wait the ~20 seconds. I'm waiting for that beeping noise to go away. Well, it goes away all right -- right as the game segfaults and dies.

**Comment by stephengtuggy** [comment]
Text version of gdb stack trace:

```
#0  0x00000000007a047a in SharedPool<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, StringpoolTraits>::Reference::get (this=0x368)
    at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/SharedPool.h:121
#1  SharedPool<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, StringpoolTraits>::Reference::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const& (this=0x368) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/SharedPool.h:123
#2  Pilot::getAnger (this=<optimized out>, parent=parent@entry=0x3051be0, target=target@entry=0x0) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/pilot.cpp:107
#3  0x00000000007a0a5d in Pilot::GetEffectiveRelationship (this=<optimized out>, parent=parent@entry=0x3051be0, target=0x0)
    at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/pilot.cpp:132
#4  0x000000000093239b in Unit::getRelation (this=this@entry=0x3051be0, targ=<optimized out>) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/unit_generic.cpp:1912
#5  0x0000000000b791c9 in UnitWrapper::getRelation (this=<optimized out>, other=...) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/unit_generic.h:1326
#6  0x0000000000b751b8 in boost::python::detail::invoke<boost::python::to_python_value<float const&>, float (UnitWrapper::*)(UnitWrapper), boost::python::arg_from_python<UnitWrapper&>, boost::python::arg_from_python<UnitWrapper> > (ac0=..., tc=<synthetic pointer>..., f=@0x5012cb8: (float (UnitWrapper::*)(UnitWrapper * const, UnitWrapper)) 0xb7916c <UnitWrapper::getRelation(UnitWrapper)>, rc=...)
    at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/container.h:18
#7  boost::python::detail::caller_arity<2u>::impl<float (UnitWrapper::*)(UnitWrapper), boost::python::default_call_policies, boost::mpl::vector3<float, UnitWrapper&, UnitWrapper> >::operator() (
    args_=<optimized out>, this=0x5012cb8) at /usr/include/boost/python/detail/caller.hpp:216
#8  boost::python::objects::caller_py_function_impl<boost::python::detail::caller<float (UnitWrapper::*)(UnitWrapper), boost::python::default_call_policies, boost::mpl::vector3<float, UnitWrapper&, UnitWrapper> > >::operator() (this=0x5012cb0, args=<optimized out>, kw=<optimized out>) at /usr/include/boost/python/object/py_function.hpp:38
#9  0x00007ffff7a37e5b in boost::python::objects::function::call(_object*, _object*) const () from /lib/x86_64-linux-gnu/libboost_python38.so.1.67.0
#10 0x00007ffff7a3810c in ?? () from /lib/x86_64-linux-gnu/libboost_python38.so.1.67.0
#11 0x00007ffff7a3d1d3 in boost::python::handle_exception_impl(boost::function0<void>) () from /lib/x86_64-linux-gnu/libboost_python38.so.1.67.0
#12 0x00007ffff7a356b6 in ?? () from /lib/x86_64-linux-gnu/libboost_python38.so.1.67.0
#13 0x00007ffff7d007db in _PyObject_MakeTpCall () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#14 0x00007ffff7d00aa0 in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#15 0x00007ffff7accd6d in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#16 0x00007ffff7ad4ef6 in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#17 0x00007ffff7ad806b in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#18 0x00007ffff7accd6d in ?? () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#19 0x00007ffff7ad4ef6 in _PyEval_EvalFrameDefault () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#20 0x00007ffff7c22d3b in _PyEval_EvalCodeWithName () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#21 0x00007ffff7c230c2 in PyEval_EvalCodeEx () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#22 0x00007ffff7c234af in PyEval_EvalCode () from /lib/x86_64-linux-gnu/libpython3.8.so.1.0
#23 0x00000000009df40c in CompileRunPython (filename="modules/dj.py") at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/python/python_compile.cpp:113
#24 0x00000000007624c5 in Music::SelectTracks (this=0x19f8a88, layer=-1) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/music.cpp:272
#25 0x0000000000762869 in Music::_Skip (this=this@entry=0x19f8a88, layer=layer@entry=-1) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/music.cpp:672
#26 0x0000000000762fb6 in Music::Listen (this=0x19f8a88) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/music.cpp:455
#27 0x000000000076301c in Music::MuzakCycle () at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/cmd/music.cpp:740
#28 0x0000000000482d90 in main_loop () at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/main_loop.cpp:1018
#29 0x000000000081cc99 in winsys_process_events () at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/gldrv/winsys.cpp:539
#30 0x00000000007fbd8c in GFXLoop (main_loop=main_loop@entry=0x81dbbe <bootstrap_first_loop()>) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/gldrv/gl_init.cpp:748
#31 0x00000000004a778c in Universe::Loop (this=<optimized out>, main_loop=main_loop@entry=0x81dbbe <bootstrap_first_loop()>)
    at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/universe.cpp:356
#32 0x0000000000827c7d in main (argc=2, argv=<optimized out>) at /home/stephen/projects/repos/git/GitHub/Vega-Strike-Engine-Source/engine/src/main.cpp:433
```
